function Dashboard() {
  const stats = [
    { label: 'Total Savings', value: 'UGX 2.5M', color: 'text-[--color-primary-green]', sub: '+12% from last month' },
    { label: 'Saved Selections', value: '12', color: 'text-[--color-primary-blue-soft]', sub: 'Across 4 facilities' },
    { label: 'Active Tasks', value: '4', color: 'text-white', sub: 'Processing now' }
  ];

  const rows = [
    { date: 'Feb 15, 2026', task: 'Main Office Lobby', machine: 'SuperScrub 2000', status: 'Optimized' },
    { date: 'Feb 12, 2026', task: 'Warehouse Floor', machine: 'HeavyDuty Industrial', status: 'Active' },
    { date: 'Feb 10, 2026', task: 'Food Processing', machine: 'HygieClean Pro', status: 'Completed' }
  ];

  return (
    <div className="max-w-6xl mx-auto px-6 pb-24 space-y-16">
      <section className="surface-panel p-10 space-y-6">
        <div>
          <p className="tag-chip border-white/30">Overview</p>
          <h1 className="text-5xl font-black text-white mt-4">Executive Dashboard</h1>
          <p className="text-white/70 mt-2">Monitor savings, selections, and live intelligence.</p>
        </div>
        <div className="grid md:grid-cols-3 gap-6">
          {stats.map((stat) => (
            <div key={stat.label} className="surface-card p-6 space-y-3">
              <p className="text-[10px] uppercase tracking-[0.4em] text-white/40">{stat.label}</p>
              <p className={`text-4xl font-black ${stat.color}`}>{stat.value}</p>
              <p className="text-sm text-white/60">{stat.sub}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="surface-panel p-10 space-y-6">
        <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
          <div>
            <h2 className="text-3xl font-black text-white">Recent Recommendations</h2>
            <p className="text-white/60 text-sm mt-2">Latest intelligence generated by CleanMatch DSS.</p>
          </div>
          <button className="outline-button">Export Analytics</button>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="text-[10px] uppercase tracking-[0.35em] text-white/40">
                <th className="px-6 py-4 border-b border-white/10">Timestamp</th>
                <th className="px-6 py-4 border-b border-white/10">Operation Task</th>
                <th className="px-6 py-4 border-b border-white/10">AI Asset Match</th>
                <th className="px-6 py-4 border-b border-white/10 text-right">Status</th>
              </tr>
            </thead>
            <tbody className="text-white/80">
              {rows.map((row, index) => (
                <tr key={index} className="even:bg-white/5">
                  <td className="px-6 py-6 font-semibold">{row.date}</td>
                  <td className="px-6 py-6 text-2xl font-black">{row.task}</td>
                  <td className="px-6 py-6 text-[--color-primary-green] font-black">{row.machine}</td>
                  <td className="px-6 py-6 text-right">
                    <span className="text-sm uppercase tracking-[0.3em]">{row.status}</span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>
    </div>
  );
}

export default Dashboard;
